### ISSUE TITLE
Send instructions about installation ... to participants

### ISSUE THREAD

**Issue by nickhaf** [nickhaf/r_tutorial#10]

**Comment by MalikaIhle** [comment]
could they do this in the session instead? or does it take too much time?
some won't do it in advance anyway, some will ask whether they need to update their R and how to do it, some will encounter issues and need help, some will install it in their onedrive instead of local, etc.

**Comment by MalikaIhle** [comment]
if instructions need to be sent in advance, I can do that on ~5 september. 
just the link to the set up page right?

**Comment by nickhaf** [comment]
How do the other workshops handle this? 
I think we can send the instructions in advance and plan the workshop with the software already installed. Participants who didn't install it can still do so, as it is a self paced workshop anyways.

**Comment by MalikaIhle** [comment]
I will make them install Git within the workshop given they sometimes struggle. But Aaron, for the Julia workshop, also wanted to send instructions in advance.

We can do that for both your workshops. the other workshops don't need installation. 
I'll need the instructions before Sept 5

**Comment by MalikaIhle** [comment]
is that enough for you?

Instructions for all attendees
You need to have admin rights to your computer in order to install software:
* All attendees: please install R and RStudio: https://posit.co/download/rstudio-desktop/ 
* Attendees to the Julia workshop: please install Julia, VSCode and Julia extension for VSCode following these instructions: https://formal-methods-mpi.github.io/Workshop.jl/stable/0_preparation/preparation/ 
Other software (namely Git) will be installed during the workshops.

**Comment by nickhaf** [comment]
Maybe add a mention of posit cloud, in case participants don't want or can install anything? A Short Intro can be found in the tip box in this chapter: https://nickhaf.github.io/r_tutorial/qmd/setup/setup.html#installation

**Comment by MalikaIhle** [comment]
All attendees: please install R and RStudio following these instructions: https://nickhaf.github.io/r_tutorial/qmd/setup/setup.html#installation

should cover all then. Though I did tell them upon acceptance that they needed admin rights - for the Git workshop, they'll need it and need RStudio installed... (to match the current material)

**Comment by nickhaf** [comment]
Should i remove the mention of posit cloud totally, so they already install R for the git workshop?

**Comment by MalikaIhle** [comment]
can be good to know for them (for later people who will take the workshop independently). 
Perhaps I can go back to 
All attendees: please install R and RStudio: https://posit.co/download/rstudio-desktop/ in the instructions and you don't change a thing in the tutorial?

**Comment by nickhaf** [comment]
Okay, let's do that.

**Comment by nickhaf** [comment]
@MalikaIhle : Can I close this?

**Comment by MalikaIhle** [comment]
yes!
