### ISSUE TITLE
load data

### ISSUE THREAD

**Issue by MalikaIhle** [nickhaf/r_tutorial#59]
there could be more explanation on how to download the data in this paragraph: https://nickhaf.github.io/r_tutorial/qmd/getting_started/the_big_picture.html#load-data given the hyperlink isn't pointing to the  specific file.
also it's a RDS file, which is new, maybe a mention that this can only be opened in rstudio is worth it (I'm not sure I would save raw data this way outside of this workshop, for the sake of generality)

**Comment by MalikaIhle** [comment]
also the function ReadRDS already assume you've worked in RStudio before so that wouldn't be the typical function to call data for the first time?

**Comment by nickhaf** [comment]
I don't quite understand your second comment. What would you suggest as an alternative function call?

**Comment by nickhaf** [comment]
Aah, did you mean it would be better to load a `.csv` file?

**Comment by MalikaIhle** [comment]
well maybe, because if you never worked with RStudio there shouldn't be any RDS file on your laptop and anyway, you wouldn't save a raw file for sharing in RDS for the sake of being interoperable through the ages? what do you think?
it just felt a bit funny that the first command to learn how to load a data file was this one. the read csv is likely more common?

**Comment by nickhaf** [comment]
Yes I agree. I chose the `.rds` file to stay within the R-cosmos, but it makes sense to start the Intor with something familiar. Will change.
